[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.15.0", features = ["derive"] }
minifb = "0.25.0"
num-traits = "0.2.18"
renderer_macros = { path = "../renderer_macros" }
