[package]
name = "renderer_types"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
num-traits = { workspace = true }
renderer_macros = { version = "0.1.0", path = "../renderer_macros" }
